version: "3.4"

services:
  test:
    build: .
    container_name: test
    command: tail -f /dev/null
    networks:
      - rest

  jenkins:
    build: ./jenkins/
    container_name: jenkins
    user: root
    privileged: true
    pull_policy: never
    env_file: .env
    environment:
      - JENKINS_ADMIN_ID:$JENKINS_ADMIN_ID
      - JENKINS_ADMIN_PASSWORD:JENKINS_ADMIN_PASSWORD
    ports:
      - 8085:8080
      - 50000:50000
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - rest

networks:
  rest:

volumes:
  jenkins_home:
